[Variables]
size=2
n=6

; COLORS
black		=10,10,10
white		=240,240,240
grey		=35,35,35
grey1		=15,15,15
grey2		=22,22,22
tapecolor	=100,100,100,100
noteline	=76,172,249
notemargin	=244,88,89
noteink		=0,20,200

red			=255,50,50
green		=0,220,80
yellow		=250,220,10
orange		=255,150,0
blue1		=0,225,225
blue2		=0,150,225

grad1		= 0 | 244,127,232 ; 0.10 | 141,238,233 ; 0.85
gradGrey1 = 180 | 15,15,15,240 ; 0 | 15,15,15 ; 0.2 | 15,15,15 ; 0.8 | 15,15,15,240 ; 1
gradGrey2 = 180 | 22,22,22,220 ; 0 | 22,22,22 ; 0.2 | 22,22,22 ; 0.8 | 22,22,22,240 ; 1

; TIME TABLE
A		="A Automata Theory"
B		="B Comp Networks"
C		="C System Software"
D		="D Microprocessors"
E		="E Software Sys Mgmt"
F		="F Disaster Mgmt"
brek	="Break Time"
S		="Microprocessor Lab"
T		="DBMS Lab"

AColor		=#red#
BColor		=#green#
CColor		=#yellow#
DColor		=#orange#
EColor		=#blue1#
FColor		=#blue2#
brekColor	=#grey#
SColor		=#green#
TColor		=#orange#

//////////////////////////////////////////////////////////////


;     M O N D A Y     ;
;---------------------;

; SUBJECTS
Monday1		=#E#
Monday2		=#B#
Monday3		=#A#
Monday4		=#D#
Monday5		=#C#
Monday6		=#D#
Monday7		=" "
Monday8		=" "
Monday9		=" "

; TIME
Mondayt1	=930
Mondayt2	=1020
Mondayt3	=1120
Mondayt4	=1240
Mondayt5	=130
Mondayt6	=230
Mondayt7	=" "
Mondayt8	=" "
Mondayt9	=" "

; COLOR
MondayColor1	=#EColor#
MondayColor2	=#BColor#
MondayColor3	=#AColor#
MondayColor4	=#DColor#
MondayColor5	=#CColor#
MondayColor6	=#DColor#
MondayColor7	=#CColor#
MondayColor8	=#CColor#
MondayColor9	=#CColor#


;    T U E S D A Y    ;
;---------------------;

; SUBJECTS
Tuesday1	=#S#
Tuesday2	=#S#
Tuesday3	=#S#
Tuesday4	=#S#
Tuesday5	=#F#
Tuesday6	=#F#
Tuesday7	=" "
Tuesday8	=" "
Tuesday9	=" "

; TIME
Tuesdayt1	=930
Tuesdayt2	=1020
Tuesdayt3	=1120
Tuesdayt4	=1240
Tuesdayt5	=130
Tuesdayt6	=230
Tuesdayt7	=" "
Tuesdayt8	=" "
Tuesdayt9	=" "

; COLOR
TuesdayColor1	=#SColor#
TuesdayColor2	=#SColor#
TuesdayColor3	=#SColor#
TuesdayColor4	=#SColor#
TuesdayColor5	=#FColor#
TuesdayColor6	=#FColor#
TuesdayColor7	=#TColor#
TuesdayColor8	=#TColor#
TuesdayColor9	=#TColor#


;  W E D N E S D A Y  ;
;---------------------;

; SUBJECTS
Wednesday1	=#B#
Wednesday2	=#A#
Wednesday3	=#C#
Wednesday4	=#E#
Wednesday5	=#A#
Wednesday6	=#C#
Wednesday7	=" "
Wednesday8	=" "
Wednesday9	=" "

; TIME
Wednesdayt1	=930
Wednesdayt2	=1020
Wednesdayt3	=1120
Wednesdayt4	=1240
Wednesdayt5	=130
Wednesdayt6	=230
Wednesdayt7	=" "
Wednesdayt8	=" "
Wednesdayt9	=" "

; COLOR
WednesdayColor1	=#BColor#
WednesdayColor2	=#AColor#
WednesdayColor3	=#CColor#
WednesdayColor4	=#EColor#
WednesdayColor5	=#AColor#
WednesdayColor6	=#CColor#
WednesdayColor7	=#DColor#
WednesdayColor8	=#DColor#
WednesdayColor9	=#DColor#


;   T H U R S D A Y   ;
;---------------------;

; SUBJECTS
Thursday1	=#B#
Thursday2	=#B#
Thursday3	=#D#
Thursday4	=#E#
Thursday5	=#E#
Thursday6	=#D#
Thursday7	=" "
Thursday8	=" "
Thursday9	=" "

; TIME
Thursdayt1	=930
Thursdayt2	=1020
Thursdayt3	=1120
Thursdayt4	=1240
Thursdayt5	=130
Thursdayt6	=230
Thursdayt7	=" "
Thursdayt8	=" "
Thursdayt9	=" "

; COLOR
ThursdayColor1	=#BColor#
ThursdayColor2	=#BColor#
ThursdayColor3	=#DColor#
ThursdayColor4	=#EColor#
ThursdayColor5	=#EColor#
ThursdayColor6	=#DColor#
ThursdayColor7	=#AColor#
ThursdayColor8	=#AColor#
ThursdayColor9	=#AColor#


;     F R I D A Y     ;
;---------------------;

; SUBJECTS
Friday1		=#T#
Friday2		=#T#
Friday3		=#T#
Friday4		=#T#
Friday5		=#A#
Friday6		=#C#
Friday7		=" "
Friday8		=" "
Friday9		=" "

; TIME
Fridayt1	=930
Fridayt2	=1015
Fridayt3	=1120
Fridayt4	=1155
Fridayt5	=140
Fridayt6	=225
Fridayt7	=" "
Fridayt8	=" "
Fridayt9	=" "

; COLOR
FridayColor1 	=#TColor#
FridayColor2	=#TColor#
FridayColor3	=#TColor#
FridayColor4	=#TColor#
FridayColor5	=#AColor#
FridayColor6	=#CColor#
FridayColor7	=#BColor#
FridayColor8	=#BColor#
FridayColor9	=#BColor#


;   S A T U R D A Y   ;
;---------------------;

; SUBJECTS
Saturday1	="Nothing to do :)"
Saturday2	=" "
Saturday3	=" "
Saturday4	=" "
Saturday5	=" "
Saturday6	=" "
Saturday7	=" "
Saturday8	=" "
Saturday9	=" "

; TIME
Saturdayt1	=|_|>
Saturdayt2	=" "
Saturdayt3	=" "
Saturdayt4	=" "
Saturdayt5	=" "
Saturdayt6	=" "
Saturdayt7	=" "
Saturdayt8	=" "
Saturdayt9	=" "

; COLOR
SaturdayColor1	=#brekColor#
SaturdayColor2	=#brekColor#
SaturdayColor3	=#brekColor#
SaturdayColor4	=#brekColor#
SaturdayColor5	=#brekColor#
SaturdayColor6	=#brekColor#
SaturdayColor7	=#brekColor#
SaturdayColor8	=#brekColor#
SaturdayColor9	=#brekColor#


;     S U N D A Y     ;
;---------------------;

; SUBJECTS
Sunday1		="Nothing to do :)"
Sunday2		=" "
Sunday3		=" "
Sunday4		=" "
Sunday5		=" "
Sunday6		=" "
Sunday7		=" "
Sunday8		=" "
Sunday9		=" "

; TIME
Sundayt1	=|_|>
Sundayt2	=" "
Sundayt3	=" "
Sundayt4	=" "
Sundayt5	=" "
Sundayt6	=" "
Sundayt7	=" "
Sundayt8	=" "
Sundayt9	=" "

; COLOR
SundayColor1	=#brekColor#
SundayColor2	=#brekColor#
SundayColor3	=#brekColor#
SundayColor4	=#brekColor#
SundayColor5	=#brekColor#
SundayColor6	=#brekColor#
SundayColor7	=#brekColor#
SundayColor8	=#brekColor#
SundayColor9	=#brekColor#

//////////////////////////////////////////////////////////////

DayOffset=0
