[Variables]
size=2
n=5

; COLORS
black		=10,10,10
white		=240,240,240
grey		=35,35,35
grey1		=15,15,15
grey2		=22,22,22
tapecolor	=100,100,100,100
noteline	=76,172,249
notemargin	=244,88,89

red			=255,50,50
green		=0,220,80
yellow		=250,220,10
orange		=255,150,0
blue1		=0,225,225
blue2		=0,150,225

grad1		= 0 | 244,127,232 ; 0.10 | 141,238,233 ; 0.85
gradGrey1 = 180 | 15,15,15,240 ; 0 | 15,15,15 ; 0.2 | 15,15,15 ; 0.8 | 15,15,15,240 ; 1
gradGrey2 = 180 | 22,22,22,220 ; 0 | 22,22,22 ; 0.2 | 22,22,22 ; 0.8 | 22,22,22,240 ; 1

; TIME TABLE
A		="A Graph Theory"
B		="B Comp Architecture"
C		="C DBMS"
D		="D Operating System"
E		="E Professional Ethics"
F		="F Constitution India"
brek	="Break Time"
S		="Digital Lab"
T		="OS Lab"

AColor		=#red#
BColor		=#green#
CColor		=#yellow#
DColor		=#orange#
EColor		=#blue1#
FColor		=#blue2#
brekColor	=#grey#
SColor		=#green#
TColor		=#orange#

//////////////////////////////////////////////////////////////


;     M O N D A Y     ;
;---------------------;

; SUBJECTS
Monday1		=#A#
Monday2		=#B#
Monday3		=#D#
Monday4		=#E#
Monday5		=#C#
Monday6		=" "

; TIME
Mondayt1	=830
Mondayt2	=930
Mondayt3	=1030
Mondayt4	=1130
Mondayt5	=1230
Mondayt6	=1325

; COLOR
MondayColor1	=#AColor#
MondayColor2	=#BColor#
MondayColor3	=#DColor#
MondayColor4	=#EColor#
MondayColor5	=#CColor#
MondayColor6	=#CColor#


;    T U E S D A Y    ;
;---------------------;

; SUBJECTS
Tuesday1	=#A#
Tuesday2	=#F#
Tuesday3	=#T#
Tuesday4	=#T#
Tuesday5	=#T#
Tuesday6	=" "

; TIME
Tuesdayt1	=830
Tuesdayt2	=930
Tuesdayt3	=1030
Tuesdayt4	=1130
Tuesdayt5	=1230
Tuesdayt6	=1325

; COLOR
TuesdayColor1	=#AColor#
TuesdayColor2	=#FColor#
TuesdayColor3	=#TColor#
TuesdayColor4	=#TColor#
TuesdayColor5	=#TColor#
TuesdayColor6	=#TColor#


;  W E D N E S D A Y  ;
;---------------------;

; SUBJECTS
Wednesday1		=#C#
Wednesday2		=#A#
Wednesday3		=#E#
Wednesday4		=#B#
Wednesday5		=#D#
Wednesday6		=" "

; TIME
Wednesdayt1		=830
Wednesdayt2		=930
Wednesdayt3		=1030
Wednesdayt4		=1130
Wednesdayt5		=1230
Wednesdayt6		=1325

; COLOR
WednesdayColor1		=#CColor#
WednesdayColor2		=#AColor#
WednesdayColor3		=#EColor#
WednesdayColor4		=#BColor#
WednesdayColor5		=#DColor#
WednesdayColor6		=#DColor#


;   T H U R S D A Y   ;
;---------------------;

; SUBJECTS
Thursday1		=#D#
Thursday2		=#C#
Thursday3		=#F#
Thursday4		=#S#
Thursday5		=#S#
Thursday6		=" "

; TIME
Thursdayt1		=830
Thursdayt2		=930
Thursdayt3		=1030
Thursdayt4		=1130
Thursdayt5		=1230
Thursdayt6		=1325

; COLOR
ThursdayColor1		=#DColor#
ThursdayColor2		=#CColor#
ThursdayColor3		=#FColor#
ThursdayColor4		=#SColor#
ThursdayColor5		=#SColor#
ThursdayColor6		=#AColor#


;     F R I D A Y     ;
;---------------------;

; SUBJECTS
Friday1		=#B#
Friday2		=#A#
Friday3		=#C#
Friday4		=#D#
Friday5		=#B#
Friday6		=" "

; TIME
Fridayt1	=800
Fridayt2	=900
Fridayt3	=1000
Fridayt4	=1100
Fridayt5	=1200
Fridayt6	=1300

; COLOR
FridayColor1 	=#BColor#
FridayColor2	=#AColor#
FridayColor3	=#CColor#
FridayColor4	=#DColor#
FridayColor5	=#BColor#
FridayColor6	=#BColor#


;   S A T U R D A Y   ;
;---------------------;

; SUBJECTS
Saturday1		="Nothing to do :)"
Saturday2		=" "
Saturday3		=" "
Saturday4		=" "
Saturday5		=" "
Saturday6		=" "

; TIME
Saturdayt1		=|_|>
Saturdayt2		=" "
Saturdayt3		=" "
Saturdayt4		=" "
Saturdayt5		=" "
Saturdayt6		=" "

; COLOR
SaturdayColor1		=#brekColor#
SaturdayColor2		=#brekColor#
SaturdayColor3		=#brekColor#
SaturdayColor4		=#brekColor#
SaturdayColor5		=#brekColor#
SaturdayColor6		=#brekColor#


;     S U N D A Y     ;
;---------------------;

; SUBJECTS
Sunday1		="Nothing to do :)"
Sunday2		=" "
Sunday3		=" "
Sunday4		=" "
Sunday5		=" "
Sunday6		=" "

; TIME
Sundayt1		=|_|>
Sundayt2		=" "
Sundayt3		=" "
Sundayt4		=" "
Sundayt5		=" "
Sundayt6		=" "

; COLOR
SundayColor1		=#brekColor#
SundayColor2		=#brekColor#
SundayColor3		=#brekColor#
SundayColor4		=#brekColor#
SundayColor5		=#brekColor#
SundayColor6		=#brekColor#

//////////////////////////////////////////////////////////////

DayOffset=0
