[Variables]

A			="Graph Theory"
B			="Comp. Architecture"
C			="DBMS"
D			="Operating System"
E			="Professional Ethics"
F			="Constitution of India"
brek		="Break Time"
S			="Digital Lab"
T			="OS Lab"

AColor		=207,37,24
BColor		=71,194,33
CColor		=203,184,16
DColor		=241,125,0
EColor		=77,182,166
FColor		=0,153,219
brekColor	=50,50,50
SColor		=71,194,33
TColor		=241,125,0

white		=255,255,255
grey		=97,97,97
grey1		=0,0,0,150
grey2		=0,0,0,100

//////////////////////////////////////////////////////////////

;MONDAY
;----------------------
Monday			=#A#
Monday2			=#D#
Monday3			=#brek#
Monday4			=#B#
Monday5			=#E#
Monday6			=#C#

MondayColor			=#AColor#
MondayColor2		=#DColor#
MondayColor3		=#brekColor#
MondayColor4		=#BColor#
MondayColor5		=#EColor#
MondayColor6		=#CColor#

;TUESDAY
;----------------------
Tuesday			=#E#
Tuesday2		=#F#
Tuesday3		=#brek#
Tuesday4		=#T#
Tuesday5		=#T#
Tuesday6		=#T#

TuesdayColor		=#EColor#
TuesdayColor2		=#FColor#
TuesdayColor3		=#brekColor#
TuesdayColor4		=#TColor#
TuesdayColor5		=#TColor#
TuesdayColor6		=#TColor#


;WEDNESDAY
;----------------------
Wednesday		=#A#
Wednesday2		=#C#
Wednesday3		=#brek#
Wednesday4		=#E#
Wednesday5		=#B#
Wednesday6		=#D#

WednesdayColor		=#AColor#
WednesdayColor2		=#CColor#
WednesdayColor3		=#brekColor#
WednesdayColor4		=#EColor#
WednesdayColor5		=#BColor#
WednesdayColor6		=#DColor#

;THURSDAY
;----------------------
Thursday		=#D#
Thursday2		=#C#
Thursday3		=#brek#
Thursday4		=#F#
Thursday5		=#C#
Thursday6		=#A#

ThursdayColor		=#DColor#
ThursdayColor2		=#CColor#
ThursdayColor3		=#brekColor#
ThursdayColor4		=#FColor#
ThursdayColor5		=#CColor#
ThursdayColor6		=#AColor#

;FRIDAY
;----------------------
Friday		=#B#
Friday2		=#A#
Friday3		=#C#
Friday4		=#brek#
Friday5		=#D#
Friday6		=#B#

FridayColor 		=#BColor#
FridayColor2		=#AColor#
FridayColor3		=#CColor#
FridayColor4		=#brekColor#
FridayColor5		=#DColor#
FridayColor6		=#BColor#

;SATURDAY
;----------------------
Saturday		=#B#
Saturday2		=#F#
Saturday3		=#brek#
Saturday4		=#S#
Saturday5		=#S#
Saturday6		=#S#

SaturdayColor		=#BColor#
SaturdayColor2		=#FColor#
SaturdayColor3		=#brekColor#
SaturdayColor4		=#SColor#
SaturdayColor5		=#SColor#
SaturdayColor6		=#SColor#

//////////////////////////////////////////////////////////////

;TIME [Mon,Tue,Wed,Thu,Sat]
;----------------------
t1		=830
t2		=925
t3		=1020
t4		=1050
t5		=1145
t6		=1240

;[Fri]
tf		=800
tf2		=850
tf3		=940
tf4		=1030
tf5		=1100
tf6		=1150
